In [12]:
import matplotlib.pyplot as plt
import networkx as nx
import pandas as pd

Write the code to display the names (not the codes) of the top 10 airports that have the highest number of outgoing flights. Use the datasets from the class program.

In [18]:
# Load airport data
airport_cols = ["ID", "Name", "City", "Country", "IATA", "ICAO", "Lat", "Lon", "Alt", "TZ", "DST", "Tz_Type", "Source"]
airports = pd.read_csv("https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat", names=airport_cols, index_col=0, na_values="\\N")
airports.head()

,ID,Name,City,Country,IATA,ICAO,Lat,Lon,Alt,TZ,DST,Tz_Type,Source
1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10.0,U,Pacific/Port_Moresby,airport,OurAirports
2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10.0,U,Pacific/Port_Moresby,airport,OurAirports
3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10.0,U,Pacific/Port_Moresby,airport,OurAirports
4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10.0,U,Pacific/Port_Moresby,airport,OurAirports
5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10.0,U,Pacific/Port_Moresby,airport,OurAirports

In [19]:
# Load route data
route_cols = ["Airline", "Airline_ID", "Source_Airport", "Source_ID", "Dest_Airport", "Dest_ID", "Codeshare", "Stops", "Equip"]
routes = pd.read_csv("https://raw.githubusercontent.com/jpatokal/openflights/master/data/routes.dat", names=route_cols, na_values="\\N")
routes.head()

,Airline,Airline_ID,Source_Airport,Source_ID,Dest_Airport,Dest_ID,Codeshare,Stops,Equip
0,2B,410.0,AER,2965.0,KZN,2990.0,NaN,0,CR2
1,2B,410.0,ASF,2966.0,KZN,2990.0,NaN,0,CR2
2,2B,410.0,ASF,2966.0,MRV,2962.0,NaN,0,CR2
3,2B,410.0,CEK,2968.0,KZN,2990.0,NaN,0,CR2
4,2B,410.0,CEK,2968.0,OVB,4078.0,NaN,0,CR2

In [15]:
# Clean: Remove routes where we don"t have the IATA code
routes = routes.dropna(subset=["Source_Airport", "Dest_Airport"])

In [16]:
# Build multi_directional graph
G = nx.from_pandas_edgelist(routes, source="Source_Airport", target="Dest_Airport", create_using=nx.MultiDiGraph())

In [17]:
# Calculate out-degrees
out_degrees = G.out_degree() 

# Sort the nodes by their out-degree and slice top-10
top_10_airports = sorted(out_degrees, key=lambda x: x[1], reverse=True)[:10]

print("Top 10 Airports by Outgoing Flights:")
for rank, (airport, flight_count) in enumerate(top_10_airports, 1):
    print(f"{rank}. {airport}: {flight_count} flights")

Top 10 Airports by Outgoing Flights:
1. ATL: 915 flights
2. ORD: 558 flights
3. PEK: 535 flights
4. LHR: 527 flights
5. CDG: 524 flights
6. FRA: 497 flights
7. LAX: 492 flights
8. DFW: 469 flights
9. JFK: 456 flights
10. AMS: 453 flights